$ErrorActionPreference='Stop'
$target='engineering/master877/MASTER877_DETERMINISTIC_PATH_CANDIDATE.ps1'
$expected='faf7277c73f18d643f886df7668be2b3c4e0801d5d5d5283f9058e6869a94373'
$actual=(Get-FileHash -LiteralPath $target -Algorithm SHA256).Hash.ToLowerInvariant();if($actual -ne $expected){throw "DETERMINISTIC_HASH_MISMATCH actual=$actual"}
$tokens=$null;$errors=$null;[void][System.Management.Automation.Language.Parser]::ParseFile((Resolve-Path $target).Path,[ref]$tokens,[ref]$errors);if(@($errors).Count){$errors|%{Write-Error ("line={0} col={1} {2}" -f $_.Extent.StartLineNumber,$_.Extent.StartColumnNumber,$_.Message)};throw "DETERMINISTIC_PARSER_FAIL count=$(@($errors).Count)"}
Write-Output 'DETERMINISTIC_PARSER_PASS=true';Write-Output "DETERMINISTIC_TESTED_PS1_SHA256=$actual";Write-Output "POWERSHELL_VERSION=$($PSVersionTable.PSVersion)"
$fake=Join-Path $env:RUNNER_TEMP 'deterministic owner';$env:LOCALAPPDATA=$fake;$root=Join-Path $fake 'TMNM\Publisher8766Golden';New-Item -ItemType Directory -Force -Path (Join-Path $root 'tmnm_fb_publisher')|Out-Null
Set-Content -LiteralPath (Join-Path $root 'article_pool_publish.py') -Value 'fixture';Set-Content -LiteralPath (Join-Path $root 'tmnm_fb_publisher\core.py') -Value 'fixture';Set-Content -LiteralPath (Join-Path $root 'tmnm_fb_publisher\adapter.py') -Value 'fixture';Set-Content -LiteralPath (Join-Path $root 'tmnm_fb_publisher\__init__.py') -Value 'fixture'
$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName='powershell.exe';$psi.Arguments="-NoProfile -ExecutionPolicy Bypass -File `"$((Resolve-Path $target).Path)`"";$psi.UseShellExecute=$false;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$psi.CreateNoWindow=$true;$p=New-Object Diagnostics.Process;$p.StartInfo=$psi;$sw=[Diagnostics.Stopwatch]::StartNew();[void]$p.Start();$first=$p.StandardOutput.ReadLine();$firstMs=$sw.ElapsedMilliseconds;if($first -ne 'MASTER877 READ-ONLY CHECK STARTED'){throw "IMMEDIATE_OUTPUT_FAIL first=$first"};if($firstMs -gt 3000){throw "IMMEDIATE_OUTPUT_SLOW ms=$firstMs"};if(-not $p.WaitForExit(30000)){try{$p.Kill()}catch{};throw 'DETERMINISTIC_RUNTIME_TIMEOUT'};$rest=$p.StandardOutput.ReadToEnd();$err=$p.StandardError.ReadToEnd();Write-Output "IMMEDIATE_OUTPUT_PASS_MS=$firstMs";Write-Output "DETERMINISTIC_RUNTIME_SECONDS=$([Math]::Round($sw.Elapsed.TotalSeconds,2))";Write-Output "DETERMINISTIC_RUNTIME_EXIT=$($p.ExitCode)";if($p.ExitCode -ne 0){throw "RUNTIME_EXIT_FAIL $err"};if(($first+"`n"+$rest) -notmatch 'Publisher8766Golden'){throw 'EXACT_PATH_RESULT_MISSING'};Write-Output 'DETERMINISTIC_RUNTIME_PASS=true'
